version: 2

jobs:
  lint_yml:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: pip install --user yamllint && yamllint co2eq/**/*.yml

  verify:
    docker:
      - image: circleci/node:10.23
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "playground/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: touch integrations/env.json
      - run: yarn --frozen-lockfile && cd playground && yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - playground/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "playground/yarn.lock" }}
      - run: yarn lint:bail
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:10.23
    steps:
      - attach_workspace:
          at: .
      - run: bash scripts/release.sh


workflows:
  version: 2
  main_workflow:
    jobs:
      - lint_yml
      - verify
      - deploy:
          requires:
            - lint_yml
            - verify
          filters:
            branches:
              only:
                - master
